### PR TITLE
Delete as much compiler directives as possible from use

### PR DESCRIPTION
**Pull request by ticotaco72**
### Purpose of this PR

1. Deleted most of uses of compiler directives, replaced these that are necessary but can be replaced by something other. Leaved some as they were e.g. in `configuration.cs` and `DEBUG` directive
1. Deleted some unused (i believe) files
1. Will delete never used code.
### Testing status

Not tested.

### CODE REVIEW

**Comment by tangalbert919** [comment]
While this may help in cleaning up the code, at the same time, you're calling for the complete removal of Android and iOS support. Unless you're going to do Samah's new structure, this would be more of a setback than an improvement.

**Comment by ticotaco72** [comment]
but as i understood we are about to do samah's new structure? i just didn't include his pr there. Anything what was here is in develop branch and can be added again. And as @ppy said we do want to delete directives if possible (or i remeber wrong)

**Comment by swoolcock** [comment]
We want to avoid directives in osu!framework.  It may be unavoidable in osuTK, but we’ll see how it goes.

**Comment by ticotaco72** [comment]
for now i deleted only them only there where they weren't necessary so it isn't a big thing i think

**Comment by swoolcock** [comment]
Does it compile for iOS and Android?  Have you tested it?

**Comment by ticotaco72** [comment]
Deleted old project files. I need to check on your new structure

**Comment by ticotaco72** [comment]
can someone send there src\graphics\es20\es20.cs , cause i cant bind it correctly

**Comment by ticotaco72** [comment]
for now i cant build osutk.ns20 cause there are a lot of errors with not found types in this file, propably because because i copied it from clean opentk 3.0

**Comment by swoolcock** [comment]
Or you could wait until I’ve fixed the merge conflicts and work from that.

**Comment by ticotaco72** [comment]
i think that's not a problem, cause i never could bind it normally with ppy's branch

**Comment by ticotaco72** [comment]
closing as i'll create new pr which is better

**Pull request closed without merging**
