### PR TITLE
Macosx64 cursor fix

### PR DESCRIPTION
**Pull request by VPeruS**
Seems to work. Window start firing events when mouse moves.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Have you thought about pull requesting this to upstream?

**Comment by VPeruS** [comment]
Need some changes with HIRect and then I pull it to them.

**Comment by varon** [comment]
We'd really love to add your contribution to OpenTK and eagerly await this PR!

**Comment by varon** [comment]
Actually - while I think about it, what's the deal here? Why does this fork exist? We'd love to get your guys stuff merged in!

**Comment by peppy** [comment]
As I mentioned earlier today to @VPeruS, our fork was mostly just a temporary thing with some hacks we had in place. We fully intend to destroy it once we are in sync with upstream. Currently we're still quite occupied with getting our game implementation complete, but I can foresee this happening not too far in the future.

At very least, the recent PRs from @VPeruS (who is doing an amazing job with cross-platform support) will not be merged here – we've already discussed and he will be submitting directly to the main repo.

**Comment by varon** [comment]
Awesome! It'll be great to have you guys on board. I'll look forward to a lot of productive future collaboration!

**Comment by peppy** [comment]
Has been merged into our temporary branch.

**Pull request closed without merging**
