### PR TITLE
Expose precise scrolling capability (macOS only) and fix cursor hiding

### LINKED ISSUE #1177: Fix cursor not hiding in .NET Standard
Cursor is not hiding correctly on macOS under a `netcoreapp2.0` target. This requires some changes to our OpenTK branch at https://github.com/ppy/opentk/tree/netstandard.

<bountysource-plugin>

---
There is a **[$90 open bounty](https://www.bountysource.com/issues/51801922-fix-cursor-not-hiding-in-net-standard?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Tom94**
In the future, precise scrolling capabilities could also get introduced to Windows. IIRC the surface (pro and book) both have precisely scrolling trackpads, for instance.

This PR also fixes cursor hiding along the way. (closes https://github.com/ppy/osu-framework/issues/1177)

### CODE REVIEW

**Comment by peppy** [comment]
I feel like we should probably be submitting these PRs to upstream opentk too, just to gauge whether it is something we can have applied there.

**Comment by Tom94** [comment]
I fully agree. It's already on my to-do list for this branch and will do so once I get the chance.

**Comment by peppy** [comment]
Looks good. I won't merge this until I'm at a PC I can push a new nuget build from.

**Review by peppy — APPROVED** [review]

**Comment by Tom94** [comment]
I am actually not 100% sure whether it wouldn't be better to include `HasPreciseScroll` in `RawMouseFlags`. The clear benefit is, that no additional member variable would be needed, however the downside is that `RawMouseFlags` is based on some Windows-specific flags, where we might introduce incompatibilities in the future. That said, the same `RawMouseFlags` is used in non-Windows operating systems, so the need for exact compatibility with the Windows header is questionable.

**Comment by Tom94** [comment]
On second look, it seems like _we_ were the ones who introduced `RawMouseFlags` in the first place. This makes me a lot less uncomfortable with completely changing the enum to no longer be windows-based and to have it include `HasPreciseScroll`.

**Comment by Tom94** [comment]
PR submitted to OpenTK _without_ a set of flags due to them not using `RawMouseFlags` at all. In the future, if we also submit our `RawMouseFlags` capabilities, we may consider merging the 2.

See https://github.com/opentk/opentk/pull/763

**Pull request merged**
